name: Build and Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node
      uses: actions/setup-node@v1
      with:
        node-version: '14'  # Set this to the node version you need

    - name: Install dependencies
      run: npm install  # If you use npm for dependencies

    - name: Build
      run: npm run build  # Replace or remove if you don't have a build step

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./numble  # Set the folder you want to deploy if necessary
