name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # This should be your default branch where you push changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./numble  # The directory that contains your index.html
          publish_branch: main  # The branch you want to deploy to
